/** Banco oficial · Lucha Libre 2 de 3 Caídas · SNEF 2026. */
const BANCO_PREGUNTAS = {
  1: {
    nombre: "¡Primera caída! · ¿QUÉ TANTO LE SABES?",
    subtitulo: "Conocimiento y Diagnóstico",
    preguntas: [
      { id: "c1_p1", pregunta: "¿Qué es una cuenta Afore?", opciones: ["Una cuenta para guardar dinero de uso diario", "Una cuenta individual donde se administran recursos para el retiro", "Una tarjeta de crédito especial", "Un seguro de vida"], correcta: 1, reflexion: "Tu cuenta Afore es individual y concentra recursos destinados a tu retiro y a tu vivienda." },
      { id: "c1_p2", pregunta: "¿Dónde puedes consultar información sobre tu cuenta Afore?", opciones: ["Únicamente con un amigo que sepa de finanzas", "En canales oficiales de CONSAR y tu Afore", "Sólo cuando te jubiles", "En cualquier red social"], correcta: 1, reflexion: "Antes de decidir, consulta información oficial." },
      { id: "c1_p3", pregunta: "¿Qué puedes revisar en tu estado de cuenta Afore?", opciones: ["Sólo tu nombre", "Información sobre saldo, aportaciones y movimientos", "Únicamente impuestos", "Tu historial de compras"], correcta: 1, reflexion: "Revisar tu estado de cuenta te ayuda a conocer mejor tu situación para tomar decisiones y mejorarla." },
      { id: "c1_p4", pregunta: "¿El dinero de tu cuenta Afore pertenece a…?", opciones: ["La empresa donde trabajas", "El gobierno", "La persona titular de la cuenta", "El banco"], correcta: 2, reflexion: "Los recursos de la cuenta individual pertenecen a la persona titular." },
      { id: "c1_p5", pregunta: "¿Cuándo conviene empezar a conocer tu cuenta Afore?", opciones: ["Sólo al cumplir 60 años", "Cuando falten cinco años para retirarte", "Desde que empiezas tu vida laboral", "Sólo si quieres cambiar de Afore"], correcta: 2, reflexion: "Mientras antes conozcas tu cuenta, más tiempo tienes para planear." },
      { id: "c1_p6", pregunta: "¿Qué institución pública regula y supervisa el sistema del ahorro para el retiro y a las Administradoras de Fondos para el Retiro (Afore) en México?", opciones: ["CONSAR", "IMSS", "SAT", "CONDUSEF"], correcta: 0, reflexion: "La Comisión Nacional del Sistema de Ahorro para el Retiro (CONSAR) es el órgano regulador encargado de emitir las reglas y supervisar el funcionamiento de las Afores." },
      { id: "c1_p7", pregunta: "¿De cuántas subcuentas principales se compone la cuenta individual del trabajador en una Afore?", opciones: ["Cinco subcuentas", "Una sola cuenta no dividida", "Dos subcuentas", "Cuatro subcuentas"], correcta: 3, reflexion: "La cuenta individual se divide en: Retiro, Cesantía en edad avanzada y Vejez (RCV); Aportaciones Voluntarias; Vivienda; y Aportaciones Complementarias." },
      { id: "c1_p8", pregunta: "¿Cuál es la herramienta gubernamental oficial en línea para localizar en qué Afore se encuentra registrada una cuenta individual?", opciones: ["Sitio web de la Profeco", "Buró de Crédito", "AforeWeb / SARTEL / Afore Móvil", "Portal de Transparencia de la SHCP"], correcta: 2, reflexion: "El portal oficial AforeWeb, Afore Móvil y la línea telefónica SARTEL (administrados en el marco del SAR) son los medios institucionales para consultar la ubicación de tu Afore." },
      { id: "c1_p9", pregunta: "¿Con qué frecuencia mínima las Afores están obligadas por ley a enviar el estado de cuenta al domicilio o correo del trabajador?", opciones: ["Una vez cada tres años", "Únicamente al momento de jubilarse", "Cada mes", "Tres veces al año"], correcta: 3, reflexion: "Por disposición legal de la CONSAR, las Afores deben emitir y enviar el estado de cuenta cuatrimestralmente (cada cuatro meses), eso hace 3 veces al año." },
      { id: "c1_p10", pregunta: "¿Qué documento oficial contiene la Clave Única de Registro de Población (CURP) y el Número de Seguridad Social (NSS) requeridos obligatoriamente para tramitar la localización o traspaso de una Afore?", opciones: ["Expediente de Identificación del Trabajador", "Constancia de Situación Fiscal exclusivamente", "Póliza de seguro de gastos médicos mayores", "Carta de recomendación laboral"], correcta: 0, reflexion: "El Expediente de Identificación Digital concentra los datos biométricos y de identificación (NSS, CURP, identificación oficial) requeridos para cualquier trámite en el SAR." },
      { id: "c1_p11", pregunta: "¿Cuántas Afores operan en México?", opciones: ["5", "2", "8", "10"], correcta: 3, reflexion: "En México operan 10 Afores encargadas de administrar el dinero de los trabajadores, 9 privadas y una pública." },
      { id: "c1_p12", pregunta: "¿Qué pasa si no elijo Afore?", opciones: ["Me asignan una automáticamente", "Nada", "No me dan mi pensión", "Me sancionan"], correcta: 0, reflexion: "Elegir Afore te permite aprovechar los beneficios que te ofrezca esta misma, además de que es más fácil mantenerte informado y realizar tus trámites." }
    ]
  },
  2: {
    nombre: "¡Segunda caída! · ¿CUÁL ES TU JUGADA?",
    subtitulo: "Estrategia y Decisión",
    preguntas: [
      { id: "c2_p1", pregunta: "Vale tiene 24 años y piensa: “Todavía falta muchísimo para el retiro. Lo veo después”. ¿Qué le aconsejarías?", opciones: ["No hacer nada hasta los 50", "Conocer desde ahora su cuenta y empezar a tomar decisiones con tiempo", "Cerrar su cuenta", "Esperar a que alguien le diga qué hacer"], correcta: 1, reflexion: "El tiempo también es parte de la planeación." },
      { id: "c2_p2", pregunta: "Alex recibe su primer estado de cuenta Afore, pero no entiende algunos datos. ¿Qué podría hacer?", opciones: ["Ignorarlo", "Preguntar en redes sociales al azar", "Consultar información oficial o a su Afore antes de decidir", "Tirarlo"], correcta: 2, reflexion: "Planear también implica entender la información antes de actuar." },
      { id: "c2_p3", pregunta: "Fer quiere empezar a pensar en su retiro, pero siente que debe resolver todo de una vez. ¿Qué piensas que debería hacer?", opciones: ["No empezar hasta tener mucho dinero", "Dar un primer paso: conocer su cuenta y establecer un objetivo", "Pedir dinero prestado para ahorrar", "Esperar a tener más edad"], correcta: 1, reflexion: "Planear no significa resolver todo hoy. Significa empezar con información." },
      { id: "c2_p4", pregunta: "Dani tiene varios objetivos: viajar, independizarse y pensar en su retiro. ¿Qué es lo correcto que haga?", opciones: ["Renunciar a todo lo de hoy", "Ignorar completamente el futuro", "Buscar un equilibrio entre sus decisiones actuales y lo que quiere construir a largo plazo", "No hacer planes"], correcta: 2, reflexion: "Presente y futuro no tienen que estar en esquinas opuestas." },
      { id: "c2_p5", pregunta: "Sergio dice que quiere empezar a ahorrar para su futuro cerca de los 40 años porque todavía le da tiempo. ¿Crees que es lo correcto? ¿Por qué?", opciones: ["Sí, porque le da más oportunidad de comprar otras cosas", "No, porque si empieza pronto la comisión que cobra su Afore será menor", "Sí, porque lo que reciba al final será lo mismo que si empezara ahora", "No, porque el interés compuesto tendrá más tiempo de actuar en favor de él"], correcta: 3, reflexion: "El interés compuesto funciona generando ganancias sobre el dinero invertido y las mismas ganancias que va generando a lo largo del tiempo; no sólo funciona sobre el dinero invertido al principio." },
      { id: "c2_p6", pregunta: "Nadia no conoce en qué Afore está registrada su cuenta. ¿Qué harías en su lugar?", opciones: ["Investigar en canales oficiales, como SARTEL y AforeWeb", "Ignorar la situación", "Preguntarle a los vecinos", "Ir a las 10 Afores que existen a preguntar"], correcta: 0, reflexion: "SARTEL, AforeWeb y Afore Móvil son herramientas oficiales de la CONSAR para que los trabajadores puedan consultar y realizar trámites sin necesidad de ir a sucursales." },
      { id: "c2_p7", pregunta: "Pablo notó que los datos registrados en su cuenta Afore están mal. ¿Cuál debería ser su jugada?", opciones: ["Ninguna, ignorar eso", "Ir a su Afore con los datos correctos y cambiarlos", "Esperar a que empiece sus trámites de retiro para ir a cambiarlos", "Pagarle a un “asesor” para que haga el trámite"], correcta: 1, reflexion: "Lo ideal es ir pronto a la sucursal de su Afore; esto evitará problemas con los trámites y su dinero. Considera que las consultas y los trámites son gratuitos." },
      { id: "c2_p8", pregunta: "Sofía no sabe en qué Afore registrarse. ¿Qué harías tú?", opciones: ["Esperar a que alguien me diga en dónde", "Registrarme en la misma Afore que mi abuelita", "Informarme en canales oficiales sobre rendimientos y servicios", "Dejar que toda la vida me la asigne la CONSAR"], correcta: 2, reflexion: "Las Afores tienen diferentes servicios y rendimientos según la Siefore. Informarse en canales oficiales de la CONSAR y las Afores te permitirá tomar una mejor decisión." },
      { id: "c2_p9", pregunta: "Jesús tiene 12 años, pero ya empezó a pensar en su retiro. ¿Puede abrir una cuenta Afore?", opciones: ["No, sólo hasta que sea mayor de edad y tenga un empleo formal", "A cualquier edad puede abrir su cuenta Afore", "Puede abrir una cuenta Afore Niños, administrada por su padre, madre o tutor", "Es innecesario"], correcta: 2, reflexion: "Este tipo de cuentas fomenta la planificación financiera y el ahorro desde temprana edad. Se puede aportar desde $1 y, cuando tenga su cuenta individual, estos recursos se transferirán a ella." },
      { id: "c2_p10", pregunta: "Karen empezó su primer trabajo formal, pero sólo se ha enfocado en recibir su sueldo. ¿Es lo único por lo que debería preocuparse?", opciones: ["No, también debe revisar sus prestaciones, sus derechos y obligaciones laborales, y su cuenta individual", "Sí, ¿de qué más debería preocuparse?", "Yo haría lo mismo", "Sólo debe revisar sus derechos laborales"], correcta: 0, reflexion: "Al empezar tu primer trabajo formal debes estar al tanto de todo lo que te ofrece. Tu cuenta individual empieza a existir y debes estar al tanto de ella." },
      { id: "c2_p11", pregunta: "Manuel descubrió que su Afore está en quiebra. ¿Qué debería hacer?", opciones: ["Entrar en pánico", "No preocuparse, su ahorro está protegido", "Pierde su ahorro porque no tiene un respaldo institucional", "Tiene que empezar a cotizar desde cero en otra Afore"], correcta: 1, reflexion: "Tu ahorro está protegido por la CONSAR; ésta se encarga de transferir tu dinero a otra Afore." },
      { id: "c2_p12", pregunta: "María se cambió del sector público al privado. ¿Qué pasa con su cuenta individual?", opciones: ["Tiene que solicitar dos pensiones", "Elige con qué cuenta se pensiona", "Se mantiene su ahorro, sólo debe realizar el trámite de unificación de cuentas", "Pierde su ahorro"], correcta: 2, reflexion: "La unificación de cuentas es el trámite que te permite juntar los recursos ahorrados en las dos instituciones en una sola cuenta." }
    ]
  },
  3: {
    nombre: "¡Tercera y última caída! · TÚ, ¿QUÉ HARÍAS?",
    subtitulo: "Decisiones y Plenitud Futura",
    preguntas: [
      { id: "c3_p1", pregunta: "Recibes un mensaje que dice: “Yo puedo ayudarte a hacer un trámite de tu Afore. Sólo págame una comisión”. ¿Qué haces?", opciones: ["Pagas de inmediato", "Compartes tus datos", "Verificas primero en canales oficiales cómo se realiza el trámite", "Lo reenvías a tus amigos"], correcta: 2, reflexion: "Antes de entregar dinero o información, verifica." },
      { id: "c3_p2", pregunta: "Alguien te dice: “Cámbiate de Afore ya. Esta es la mejor para todos”. ¿Qué decisión tomas?", opciones: ["Cambias inmediatamente", "Comparas información oficial antes de decidir", "Le das tu contraseña", "Decides por popularidad"], correcta: 1, reflexion: "Una decisión financiera debe partir de información, no de presión." },
      { id: "c3_p3", pregunta: "Quieres fortalecer tu ahorro para el retiro, pero no sabes por dónde empezar. ¿Qué haces?", opciones: ["Ignorar el tema", "Revisar tu situación y conocer tus opciones", "Pedir un crédito", "Dejar que alguien decida por ti"], correcta: 1, reflexion: "Primero evalúa tu situación y conoce tus opciones; después decide." },
      { id: "c3_p4", pregunta: "Ves información diferente sobre ahorro para el retiro en dos redes sociales. ¿Qué haces?", opciones: ["Crees la publicación con más likes", "Compartes ambas", "Verificas la información con fuentes oficiales", "No vuelves a informarte"], correcta: 2, reflexion: "Antes de actuar, verifica la fuente." },
      { id: "c3_p5", pregunta: "En tu Afore no te están dando solución a una queja o inconformidad. ¿A dónde acudes?", opciones: ["CONDUSEF", "A ningún lado, así lo dejas", "PROFECO", "Con un amigo abogado"], correcta: 0, reflexion: "Si tu Afore no te da una solución a tu problema, acude a la CONDUSEF, que es la encargada de proteger y defender los derechos de los usuarios de cualquier servicio financiero." },
      { id: "c3_p6", pregunta: "Recibiste un bono en tu trabajo. ¿Qué puedes hacer?", opciones: ["Prestarlo a alguien que probablemente no te pague", "Destinarlo todo a tu ahorro para el retiro", "Irte de viaje", "Destinar una parte a tu ahorro para el retiro y la otra para otra cosa"], correcta: 3, reflexion: "El presente y el futuro no están peleados. Organizar bien tus finanzas te permite disfrutar de las compras de hoy sin descuidar el ahorro para tu futuro." },
      { id: "c3_p7", pregunta: "Un conocido te promete duplicar tu dinero en dos meses mediante una plataforma digital no registrada. ¿Qué acción tomarías?", opciones: ["Consultar en el SIPRES de la CONDUSEF si la entidad está regulada", "Transferir todos tus ahorros", "Dar una parte mínima de tus ahorros para ver si la plataforma sí paga", "Revisar opiniones y testimonios de dicha plataforma en sus propias redes sociales"], correcta: 0, reflexion: "El Sistema de Registro de Prestadores de Servicios Financieros te permite verificar si una empresa está legalmente autorizada para captar recursos." },
      { id: "c3_p8", pregunta: "Viste un video en una red social que asegura que puedes retirar todo el dinero de tu Afore antes de tiempo, sin cumplir los requisitos de ley, pagando una comisión a un intermediario. ¿Por qué es riesgoso seguir este consejo?", opciones: ["No es riesgoso y te permite disponer de tu dinero", "Es un fraude que afecta tu expediente personal", "Congelan tus cuentas bancarias", "Si tu Afore se entera, tienes que pagar una multa"], correcta: 1, reflexion: "Los gestores informales están esperando el momento perfecto para quitarles el dinero a los cotizantes; te exponen a fraudes, robo de identidad y consecuencias que afectarán tu futura pensión." },
      { id: "c3_p9", pregunta: "Recibes tu estado de cuenta Afore y observas movimientos no reconocidos o una baja inusual en tus registros de semanas cotizadas. ¿A qué instancia debes acudir para recibir asesoría previa, gratuita y oficial?", opciones: ["A la Secretaría de Economía", "A tu Afore o a CONDUSEF", "A PROFECO", "A un despacho privado de abogados"], correcta: 1, reflexion: "Tu Afore y CONDUSEF deben orientarte sobre estos movimientos y posteriormente ayudarte a solucionar el problema." },
      { id: "c3_p10", pregunta: "Solicitaste un cambio de Afore recientemente, pero no te conviene. ¿Puedes solicitar otro cambio?", opciones: ["No, sólo se puede después de cumplir un año de permanencia", "Sí, te puedes cambiar las veces que quieras en menos de un año", "No, pero un gestor informal te puede ayudar", "Sí, pero sólo si la otra Afore te ofrece un mayor rendimiento neto"], correcta: 3, reflexion: "El cambio de Afore se puede hacer después de cumplir un año de permanencia, pero puedes cambiarte antes sólo si te pasas a una Administradora que tenga un mayor rendimiento neto." },
      { id: "c3_p11", pregunta: "Trabajas de manera independiente. ¿Puedes ahorrar para tu retiro en una Afore?", opciones: ["Sí, por medio de aportaciones voluntarias", "Sólo si es en un banco tradicional", "Debes esperar a tener un empleo formal", "Sólo lo que juntes en tu cuenta de banco"], correcta: 0, reflexion: "La Modalidad 10 te permite abrir una cuenta como trabajador independiente que se sustenta con aportaciones voluntarias y te da acceso a seguridad social." },
      { id: "c3_p12", pregunta: "Te llaman por teléfono para informarte que tienes que realizar un trámite de retiro parcial en tu cuenta individual y recibir más dinero. ¿Qué haces?", opciones: ["Accedes a este trámite", "Proporcionas tus datos", "Entras en pánico", "Revisas tus cuentas y reportas el número y el modus operandi a CONDUSEF y a CONSAR"], correcta: 3, reflexion: "Los canales oficiales de CONSAR y las Afores no te llaman para realizar trámites; este tipo de llamadas son estafas. Infórmate siempre en canales oficiales." }
    ]
  }
};

if (typeof window !== 'undefined') window.BANCO_PREGUNTAS = BANCO_PREGUNTAS;
if (typeof module !== 'undefined' && module.exports) module.exports = BANCO_PREGUNTAS;
